//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RMS.App.Resources.HomeText", typeof(HomeText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Requisitions.
        /// </summary>
        public static string AssignRequisitions {
            get {
                return ResourceManager.GetString("AssignRequisitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladesh Computer Council.
        /// </summary>
        public static string BangladeshComputerCouncil {
            get {
                return ResourceManager.GetString("BangladeshComputerCouncil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Requisition.
        /// </summary>
        public static string CancelRequisition {
            get {
                return ResourceManager.GetString("CancelRequisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Requisition.
        /// </summary>
        public static string CompleteRequest {
            get {
                return ResourceManager.GetString("CompleteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gate Pass.
        /// </summary>
        public static string GatePass {
            get {
                return ResourceManager.GetString("GatePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Request.
        /// </summary>
        public static string MyRequest {
            get {
                return ResourceManager.GetString("MyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Requisition.
        /// </summary>
        public static string NewRequisition {
            get {
                return ResourceManager.GetString("NewRequisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Process.
        /// </summary>
        public static string OnProcess {
            get {
                return ResourceManager.GetString("OnProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request For Me.
        /// </summary>
        public static string RequestForMe {
            get {
                return ResourceManager.GetString("RequestForMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request For Other.
        /// </summary>
        public static string RequestForOther {
            get {
                return ResourceManager.GetString("RequestForOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition Queue.
        /// </summary>
        public static string RequisitionQueue {
            get {
                return ResourceManager.GetString("RequisitionQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition Status.
        /// </summary>
        public static string RequisitionsStatus {
            get {
                return ResourceManager.GetString("RequisitionsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Calendar.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Requisition.
        /// </summary>
        public static string SendRequisition {
            get {
                return ResourceManager.GetString("SendRequisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Queue.
        /// </summary>
        public static string SetupQueue {
            get {
                return ResourceManager.GetString("SetupQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Requisition.
        /// </summary>
        public static string TotalRequisition {
            get {
                return ResourceManager.GetString("TotalRequisition", resourceCulture);
            }
        }
    }
}
