// <auto-generated />
namespace RMS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_SeatCapacity_in_Vehicle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_SeatCapacity_in_Vehicle));
        
        string IMigrationMetadata.Id
        {
            get { return "201808120924569_Added_SeatCapacity_in_Vehicle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
