namespace RMS.Models.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Upazila_Seeds : DbMigration
    {
        public override void Up()
        {
            Sql(@"DELETE FROM Upazilas;
                   DBCC CHECKIDENT ('Upazilas', RESEED, 0)");

            Sql(@"SET IDENTITY_INSERT [dbo].[Upazilas] ON 

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (1, 34, N'Amtali Upazila', N'আমতলী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (2, 34, N'Bamna Upazila', N'বামনা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (3, 34, N'Barguna Sadar Upazila', N'বরগুনা সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (4, 34, N'Betagi Upazila', N'বেতাগি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (5, 34, N'Patharghata Upazila', N'পাথরঘাটা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (6, 34, N'Taltali Upazila', N'তালতলী')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (7, 35, N'Muladi Upazila', N'মুলাদি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (8, 35, N'Babuganj Upazila', N'বাবুগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (9, 35, N'Agailjhara Upazila', N'আগাইলঝরা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (10, 35, N'Barisal Sadar Upazila', N'বরিশাল সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (11, 35, N'Bakerganj Upazila', N'বাকেরগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (12, 35, N'Banaripara Upazila', N'বানাড়িপারা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (13, 35, N'Gaurnadi Upazila', N'গৌরনদী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (14, 35, N'Hizla Upazila', N'হিজলা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (15, 35, N'Mehendiganj Upazila', N'মেহেদিগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (16, 35, N'Wazirpur Upazila', N'ওয়াজিরপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (17, 35, N'Airport', N'এয়ারপোর্ট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (18, 35, N'Kawnia', N'কাউনিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (19, 35, N'Bondor Upazila', N'বন্দর')


                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (20, 36, N'Bhola Sadar Upazila', N'ভোলা সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (21, 36, N'Burhanuddin Upazila', N'বুরহানউদ্দিন')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (22, 36, N'Char Fasson Upazila', N'চর ফ্যাশন')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (23, 36, N'Daulatkhan Upazila', N'দৌলতখান')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (24, 36, N'Lalmohan Upazila', N'লালমোহন')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (25, 36, N'Manpura Upazila', N'মনপুরা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (26, 36, N'Tazumuddin Upazila', N'তাজুমুদ্দিন')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (27, 37, N'Jhalokati Sadar Upazila', N'ঝালকাঠি সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (28, 37, N'Kathalia Upazila', N'কাঁঠালিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (29, 37, N'Nalchity Upazila', N'নালচিতি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (30, 37, N'Rajapur Upazila', N'রাজাপুর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (31, 38, N'Bauphal Upazila', N'বাউফল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (32, 38, N'Dashmina Upazila', N'দশমিনা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (33, 38, N'Galachipa Upazila', N'গলাচিপা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (34, 38, N'Kalapara Upazila', N'কালাপারা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (35, 38, N'Mirzaganj Upazila', N'মির্জাগঞ্জ ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (36, 38, N'Patuakhali Sadar Upazila', N'পটুয়াখালী সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (37, 38, N'Dumki Upazila', N'ডুমকি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (38, 38, N'Rangabali Upazila', N'রাঙ্গাবালি')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (39, 39, N'Bhandaria', N'ভ্যান্ডারিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (40, 39, N'Kaukhali', N'কাউখালি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (41, 39, N'Mathbaria', N'মাঠবাড়িয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (42, 39, N'Nazirpur', N'নাজিরপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (43, 39, N'Nesarabad', N'নেসারাবাদ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (44, 39, N'Pirojpur Sadar', N'পিরোজপুর সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (45, 39, N'Zianagar', N'জিয়ানগর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (46, 40, N'Bandarban Sadar', N'বান্দরবন সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (47, 40, N'Thanchi', N'থানচি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (48, 40, N'Lama', N'লামা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (49, 40, N'Naikhongchhari', N'নাইখংছড়ি ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (50, 40, N'Ali kadam', N'আলী কদম')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (51, 40, N'Rowangchhari', N'রউয়াংছড়ি ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (52, 40, N'Ruma', N'রুমা')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (53, 41, N'Brahmanbaria Sadar Upazila', N'ব্রাহ্মণবাড়িয়া সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (54, 41, N'Ashuganj Upazila', N'আশুগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (55, 41, N'Nasirnagar Upazila', N'নাসির নগর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (56, 41, N'Nabinagar Upazila', N'নবীনগর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (57, 41, N'Sarail Upazila', N'সরাইল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (58, 41, N'Shahbazpur Town', N'শাহবাজপুর টাউন')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (59, 41, N'Kasba Upazila', N'কসবা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (60, 41, N'Akhaura Upazila', N'আখাউরা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (61, 41, N'Bancharampur Upazila', N'বাঞ্ছারামপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (62, 41, N'Bijoynagar Upazila', N'বিজয় নগর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (63, 42, N'Chandpur Sadar', N'চাঁদপুর সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (64, 42, N'Faridganj', N'ফরিদগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (65, 42, N'Haimchar', N'হাইমচর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (66, 42, N'Haziganj', N'হাজীগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (67, 42, N'Kachua', N'কচুয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (68, 42, N'Matlab Uttar', N'মতলব উত্তর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (69, 42, N'Matlab Dakkhin', N'মতলব দক্ষিণ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (70, 42, N'Shahrasti', N'শাহরাস্তি')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (71, 43, N'Anwara Upazila', N'আনোয়ারা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (72, 43, N'Banshkhali Upazila', N'বাশখালি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (73, 43, N'Boalkhali Upazila', N'বোয়ালখালি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (74, 43, N'Chandanaish Upazila', N'চন্দনাইশ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (75, 43, N'Fatikchhari Upazila', N'ফটিকছড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (76, 43, N'Hathazari Upazila', N'হাঠহাজারী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (77, 43, N'Lohagara Upazila', N'লোহাগারা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (78, 43, N'Mirsharai Upazila', N'মিরসরাই')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (79, 43, N'Patiya Upazila', N'পটিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (80, 43, N'Rangunia Upazila', N'রাঙ্গুনিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (81, 43, N'Raozan Upazila', N'রাউজান')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (82, 43, N'Sandwip Upazila', N'সন্দ্বীপ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (83, 43, N'Satkania Upazila', N'সাতকানিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (84, 43, N'Sitakunda Upazila', N'সীতাকুণ্ড')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (85, 43, N'Akborsha', N'আকবর শাহ্')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (86, 43, N'Baijid bostami', N'বাইজিদ বোস্তামী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (87, 43, N'Bakolia', N'বাকোলিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (88, 43, N'Bandar', N'বন্দর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (89, 43, N'Chandgaon', N'চাঁদগাও')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (90, 43, N'Chokbazar', N'চকবাজার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (91, 43, N'Doublemooring', N'ডাবল মুরিং')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (92, 43, N'EPZ', N'ইপিজেড')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (93, 43, N'Hali Shohor', N'হালী শহর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (94, 43, N'Kornafuli', N'কর্ণফুলি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (95, 43, N'Kotwali', N'কোতোয়ালী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (96, 43, N'Kulshi', N'কুলশি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (97, 43, N'Pahartali', N'পাহাড়তলী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (98, 43, N'Panchlaish', N'পাঁচলাইশ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (99, 43, N'Potenga', N'পতেঙ্গা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (100, 43, N'Shodhorgat', N'সদরঘাট')


                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (101, 44, N'Barura Upazila', N'বড়ুরা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (102, 44, N'Brahmanpara Upazila', N'ব্রাহ্মণপাড়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (103, 44, N'Burichong Upazila', N'বুড়িচং')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (104, 44, N'Chandina Upazila', N'চান্দিনা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (105, 44, N'Chauddagram Upazila', N'চৌদ্দগ্রাম')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (106, 44, N'Daudkandi Upazila', N'দাউদকান্দি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (107, 44, N'Debidwar Upazila', N'দেবীদ্বার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (108, 44, N'Homna Upazila', N'হোমনা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (109, 44, N'Comilla Sadar Upazila', N'কুমিল্লা সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (110, 44, N'Laksam Upazila', N'লাকসাম')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (111, 44, N'Monohorgonj Upazila', N'মনোহরগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (112, 44, N'Meghna Upazila', N'মেঘনা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (113, 44, N'Muradnagar Upazila', N'মুরাদনগর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (114, 44, N'Nangalkot Upazila', N'নাঙ্গালকোট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (115, 44, N'Comilla Sadar South Upazila', N'কুমিল্লা সদর দক্ষিণ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (116, 44, N'Titas Upazila', N'তিতাস')
                GO
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (117, 45, N'Chakaria Upazila', N'চকরিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (118, 45, N'Cox''s Bazar Sadar Upazila', N'কক্স বাজার সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (119, 45, N'Kutubdia Upazila', N'কুতুবদিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (120, 45, N'Maheshkhali Upazila', N'মহেশখালী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (121, 45, N'Ramu Upazila', N'রামু')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (122, 45, N'Teknaf Upazila', N'টেকনাফ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (123, 45, N'Ukhia Upazila', N'উখিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (124, 45, N'Pekua Upazila', N'পেকুয়া')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (125, 46, N'Feni Sadar', N'ফেনী সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (126, 46, N'Chagalnaiya', N'ছাগল নাইয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (127, 46, N'Daganbhyan', N'দাগানভিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (128, 46, N'Parshuram', N'পরশুরাম')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (129, 46, N'Fhulgazi', N'ফুলগাজি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (130, 46, N'Sonagazi', N'সোনাগাজি')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (131, 47, N'Dighinala Upazila', N'দিঘিনালা ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (132, 47, N'Khagrachhari Upazila', N'খাগড়াছড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (133, 47, N'Lakshmichhari Upazila', N'লক্ষ্মীছড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (134, 47, N'Mahalchhari Upazila', N'মহলছড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (135, 47, N'Manikchhari Upazila', N'মানিকছড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (136, 47, N'Matiranga Upazila', N'মাটিরাঙ্গা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (137, 47, N'Panchhari Upazila', N'পানছড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (138, 47, N'Ramgarh Upazila', N'রামগড়')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (139, 48, N'Lakshmipur Sadar Upazila', N'লক্ষ্মীপুর সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (140, 48, N'Raipur Upazila', N'রায়পুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (141, 48, N'Ramganj Upazila', N'রামগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (142, 48, N'Ramgati Upazila', N'রামগতি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (143, 48, N'Komol Nagar Upazila', N'কমল নগর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (144, 49, N'Noakhali Sadar Upazila', N'নোয়াখালী সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (145, 49, N'Begumganj Upazila', N'বেগমগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (146, 49, N'Chatkhil Upazila', N'চাটখিল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (147, 49, N'Companyganj Upazila', N'কোম্পানীগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (148, 49, N'Shenbag Upazila', N'শেনবাগ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (149, 49, N'Hatia Upazila', N'হাতিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (150, 49, N'Kobirhat Upazila', N'কবিরহাট ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (151, 49, N'Sonaimuri Upazila', N'সোনাইমুরি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (152, 49, N'Suborno Char Upazila', N'সুবর্ণ চর ')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (153, 50, N'Rangamati Sadar Upazila', N'রাঙ্গামাটি সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (154, 50, N'Belaichhari Upazila', N'বেলাইছড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (155, 50, N'Bagaichhari Upazila', N'বাঘাইছড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (156, 50, N'Barkal Upazila', N'বরকল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (157, 50, N'Juraichhari Upazila', N'জুরাইছড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (158, 50, N'Rajasthali Upazila', N'রাজাস্থলি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (159, 50, N'Kaptai Upazila', N'কাপ্তাই')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (160, 50, N'Langadu Upazila', N'লাঙ্গাডু')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (161, 50, N'Nannerchar Upazila', N'নান্নেরচর ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (162, 50, N'Kaukhali Upazila', N'কাউখালি')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (163, 1, N'Dhamrai Upazila', N'ধামরাই')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (164, 1, N'Dohar Upazila', N'দোহার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (165, 1, N'Keraniganj Upazila', N'কেরানীগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (166, 1, N'Nawabganj Upazila', N'নবাবগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (167, 1, N'Savar Upazila', N'সাভার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (168, 1, N'Adabor', N'আদাবর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (169, 1, N'Airport', N'বিমান বন্দর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (170, 1, N'Badda', N'বাড্ডা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (171, 1, N'Banani', N'বনানী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (172, 1, N'Bangshal', N'বংশাল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (173, 1, N'Bhashantek', N'ভাসানটেক')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (174, 1, N'Cantonment', N'ক্যান্টেনমেন্ট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (175, 1, N'Chackbazar', N'চকবাজার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (176, 1, N'Darussalam', N'দারুসালাম')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (177, 1, N'Daskhinkhan', N'দক্ষিনখান')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (178, 1, N'Demra', N'ডেমড়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (179, 1, N'Dhanmondi', N'ধানমন্ডি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (180, 1, N'Gandaria', N'গেন্ডারিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (181, 1, N'Gulshan', N'গুলশান')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (182, 1, N'Hazaribag', N'হজারীবাগ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (183, 1, N'Jatrabari', N'যাত্রাবাড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (184, 1, N'Kafrul', N'কাফরুল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (185, 1, N'Kalabagan', N'কলাবাগান')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (186, 1, N'Kamrangirchar', N'কামরাঙ্গীরচর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (187, 1, N'Khilgaon', N'খিলগাঁও')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (188, 1, N'Khilkhet', N'খিলখেত')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (189, 1, N'Kotwali', N'কোতয়ালী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (190, 1, N'Lalbag', N'লালবাগ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (191, 1, N'Mirpur Model', N'মিরপুর মডেল থানা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (192, 1, N'Mohammadpur', N'মোহাম্মদপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (193, 1, N'Motijheel', N'মতিঝিল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (194, 1, N'Mugda', N'মুগদা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (195, 1, N'New Market', N'নিউমার্কেট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (196, 1, N'Pallabi', N'পল্লবী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (197, 1, N'Paltan', N'পল্টন')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (198, 1, N'Ramna', N'রমনা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (199, 1, N'Rampura', N'রামপুরা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (200, 1, N'Rupnagar', N'রুপনগর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (201, 1, N'Sabujbag', N'সবুজবাগ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (202, 1, N'Shah Ali', N'শাহ্ আলী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (203, 1, N'Shahbag', N'শাহবাগ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (204, 1, N'Shahjahanpur', N'শাহজাহানপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (205, 1, N'Sherebanglanagar', N'শের-ই-বাংলা নগর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (206, 1, N'Shyampur', N'শ্যামপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (207, 1, N'Sutrapur', N'সুত্রাপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (208, 1, N'Tejgaon', N'তেজগাঁও')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (209, 1, N'Tejgaon I/A', N'তেজগাঁও শিল্পাঞ্চল থানা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (210, 1, N'Turag', N'তুরাগ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (211, 1, N'Uttara', N'উত্তরা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (212, 1, N'Uttara West', N'উত্তরা পশ্চিম')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (213, 1, N'Uttarkhan', N'উত্তরখান')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (214, 1, N'Vatara', N'ভাটারা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (215, 1, N'Wari', N'ওয়ারী')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (216, 2, N'Faridpur Sadar Upazila', N'ফরিদপুর সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (217, 2, N'Boalmari Upazila', N'বোয়ালমারী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (218, 2, N'Alfadanga Upazila', N'আলফাডাঙ্গা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (219, 2, N'Madhukhali Upazila', N'মধুখালি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (220, 2, N'Bhanga Upazila', N'ভাঙ্গা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (221, 2, N'Nagarkanda Upazila', N'নগরকান্ড')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (222, 2, N'Charbhadrasan Upazila', N'চরভদ্রাসন ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (223, 2, N'Sadarpur Upazila', N'সদরপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (224, 2, N'Shaltha Upazila', N'শালথা')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (225, 3, N'Gazipur Sadar-Joydebpur', N'গাজীপুর সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (226, 3, N'Kaliakior', N'কালিয়াকৈর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (227, 3, N'Kapasia', N'কাপাসিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (228, 3, N'Sripur', N'শ্রীপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (229, 3, N'Kaliganj', N'কালীগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (230, 3, N'Tongi', N'টঙ্গি')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (231, 4, N'Gopalganj Sadar Upazila', N'গোপালগঞ্জ সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (232, 4, N'Kashiani Upazila', N'কাশিয়ানি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (233, 4, N'Kotalipara Upazila', N'কোটালিপাড়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (234, 4, N'Muksudpur Upazila', N'মুকসুদপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (235, 4, N'Tungipara Upazila', N'টুঙ্গিপাড়া')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (236, 5, N'Dewanganj Upazila', N'দেওয়ানগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (237, 5, N'Baksiganj Upazila', N'বকসিগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (238, 5, N'Islampur Upazila', N'ইসলামপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (239, 5, N'Jamalpur Sadar Upazila', N'জামালপুর সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (240, 5, N'Madarganj Upazila', N'মাদারগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (241, 5, N'Melandaha Upazila', N'মেলানদাহা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (242, 5, N'Sarishabari Upazila', N'সরিষাবাড়ি ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (243, 5, N'Narundi Police I.C', N'নারুন্দি')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (244, 6, N'Astagram Upazila', N'অষ্টগ্রাম')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (245, 6, N'Bajitpur Upazila', N'বাজিতপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (246, 6, N'Bhairab Upazila', N'ভৈরব')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (247, 6, N'Hossainpur Upazila', N'হোসেনপুর ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (248, 6, N'Itna Upazila', N'ইটনা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (249, 6, N'Karimganj Upazila', N'করিমগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (250, 6, N'Katiadi Upazila', N'কতিয়াদি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (251, 6, N'Kishoreganj Sadar Upazila', N'কিশোরগঞ্জ সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (252, 6, N'Kuliarchar Upazila', N'কুলিয়ারচর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (253, 6, N'Mithamain Upazila', N'মিঠামাইন')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (254, 6, N'Nikli Upazila', N'নিকলি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (255, 6, N'Pakundia Upazila', N'পাকুন্ডা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (256, 6, N'Tarail Upazila', N'তাড়াইল')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (257, 7, N'Madaripur Sadar', N'মাদারীপুর সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (258, 7, N'Kalkini', N'কালকিনি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (259, 7, N'Rajoir', N'রাজইর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (260, 7, N'Shibchar', N'শিবচর')
                GO
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (261, 8, N'Manikganj Sadar Upazila', N'মানিকগঞ্জ সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (262, 8, N'Singair Upazila', N'সিঙ্গাইর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (263, 8, N'Shibalaya Upazila', N'শিবালয়')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (264, 8, N'Saturia Upazila', N'সাঠুরিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (265, 8, N'Harirampur Upazila', N'হরিরামপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (266, 8, N'Ghior Upazila', N'ঘিওর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (267, 8, N'Daulatpur Upazila', N'দৌলতপুর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (268, 9, N'Lohajang Upazila', N'লোহাজং')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (269, 9, N'Sreenagar Upazila', N'শ্রীনগর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (270, 9, N'Munshiganj Sadar Upazila', N'মুন্সিগঞ্জ সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (271, 9, N'Sirajdikhan Upazila', N'সিরাজদিখান')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (272, 9, N'Tongibari Upazila', N'টঙ্গিবাড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (273, 9, N'Gazaria Upazila', N'গজারিয়া')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (274, 10, N'Bhaluka', N'ভালুকা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (275, 10, N'Trishal', N'ত্রিশাল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (276, 10, N'Haluaghat', N'হালুয়াঘাট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (277, 10, N'Muktagachha', N'মুক্তাগাছা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (278, 10, N'Dhobaura', N'ধবারুয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (279, 10, N'Fulbaria', N'ফুলবাড়িয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (280, 10, N'Gaffargaon', N'গফরগাঁও')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (281, 10, N'Gauripur', N'গৌরিপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (282, 10, N'Ishwarganj', N'ঈশ্বরগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (283, 10, N'Mymensingh Sadar', N'ময়মনসিং সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (284, 10, N'Nandail', N'নন্দাইল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (285, 10, N'Phulpur', N'ফুলপুর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (286, 11, N'Araihazar Upazila', N'আড়াইহাজার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (287, 11, N'Sonargaon Upazila', N'সোনারগাঁও')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (288, 11, N'Bandar', N'বান্দার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (289, 11, N'Naryanganj Sadar Upazila', N'নারায়ানগঞ্জ সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (290, 11, N'Rupganj Upazila', N'রূপগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (291, 11, N'Siddirgonj Upazila', N'সিদ্ধিরগঞ্জ')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (292, 12, N'Belabo Upazila', N'বেলাবো')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (293, 12, N'Monohardi Upazila', N'মনোহরদি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (294, 12, N'Narsingdi Sadar Upazila', N'নরসিংদী সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (295, 12, N'Palash Upazila', N'পলাশ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (296, 12, N'Raipura Upazila, Narsingdi', N'রায়পুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (297, 12, N'Shibpur Upazila', N'শিবপুর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (298, 13, N'Kendua Upazilla', N'কেন্দুয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (299, 13, N'Atpara Upazilla', N'আটপাড়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (300, 13, N'Barhatta Upazilla', N'বরহাট্টা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (301, 13, N'Durgapur Upazilla', N'দুর্গাপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (302, 13, N'Kalmakanda Upazilla', N'কলমাকান্দা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (303, 13, N'Madan Upazilla', N'মদন')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (304, 13, N'Mohanganj Upazilla', N'মোহনগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (305, 13, N'Netrakona-S Upazilla', N'নেত্রকোনা সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (306, 13, N'Purbadhala Upazilla', N'পূর্বধলা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (307, 13, N'Khaliajuri Upazilla', N'খালিয়াজুরি')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (308, 14, N'Baliakandi Upazila', N'বালিয়াকান্দি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (309, 14, N'Goalandaghat Upazila', N'গোয়ালন্দ ঘাট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (310, 14, N'Pangsha Upazila', N'পাংশা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (311, 14, N'Kalukhali Upazila', N'কালুখালি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (312, 14, N'Rajbari Sadar Upazila', N'রাজবাড়ি সদর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (313, 15, N'Shariatpur Sadar -Palong', N'শরীয়তপুর সদর ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (314, 15, N'Damudya Upazila', N'দামুদিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (315, 15, N'Naria Upazila', N'নড়িয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (316, 15, N'Jajira Upazila', N'জাজিরা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (317, 15, N'Bhedarganj Upazila', N'ভেদারগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (318, 15, N'Gosairhat Upazila', N'গোসাইর হাট ')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (319, 16, N'Jhenaigati Upazila', N'ঝিনাইগাতি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (320, 16, N'Nakla Upazila', N'নাকলা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (321, 16, N'Nalitabari Upazila', N'নালিতাবাড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (322, 16, N'Sherpur Sadar Upazila', N'শেরপুর সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (323, 16, N'Sreebardi Upazila', N'শ্রীবরদি')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (324, 17, N'Tangail Sadar Upazila', N'টাঙ্গাইল সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (325, 17, N'Sakhipur Upazila', N'সখিপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (326, 17, N'Basail Upazila', N'বসাইল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (327, 17, N'Madhupur Upazila', N'মধুপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (328, 17, N'Ghatail Upazila', N'ঘাটাইল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (329, 17, N'Kalihati Upazila', N'কালিহাতি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (330, 17, N'Nagarpur Upazila', N'নগরপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (331, 17, N'Mirzapur Upazila', N'মির্জাপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (332, 17, N'Gopalpur Upazila', N'গোপালপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (333, 17, N'Delduar Upazila', N'দেলদুয়ার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (334, 17, N'Bhuapur Upazila', N'ভুয়াপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (335, 17, N'Dhanbari Upazila', N'ধানবাড়ি')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (336, 55, N'Bagerhat Sadar Upazila', N'বাগেরহাট সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (337, 55, N'Chitalmari Upazila', N'চিতলমাড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (338, 55, N'Fakirhat Upazila', N'ফকিরহাট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (339, 55, N'Kachua Upazila', N'কচুয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (340, 55, N'Mollahat Upazila', N'মোল্লাহাট ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (341, 55, N'Mongla Upazila', N'মংলা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (342, 55, N'Morrelganj Upazila', N'মরেলগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (343, 55, N'Rampal Upazila', N'রামপাল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (344, 55, N'Sarankhola Upazila', N'স্মরণখোলা')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (345, 56, N'Damurhuda Upazila', N'দামুরহুদা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (346, 56, N'Chuadanga-S Upazila', N'চুয়াডাঙ্গা সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (347, 56, N'Jibannagar Upazila', N'জীবন নগর ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (348, 56, N'Alamdanga Upazila', N'আলমডাঙ্গা')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (349, 57, N'Abhaynagar Upazila', N'অভয়নগর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (350, 57, N'Keshabpur Upazila', N'কেশবপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (351, 57, N'Bagherpara Upazila', N'বাঘের পাড়া ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (352, 57, N'Jessore Sadar Upazila', N'যশোর সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (353, 57, N'Chaugachha Upazila', N'চৌগাছা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (354, 57, N'Manirampur Upazila', N'মনিরামপুর ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (355, 57, N'Jhikargachha Upazila', N'ঝিকরগাছা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (356, 57, N'Sharsha Upazila', N'সারশা')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (357, 58, N'Jhenaidah Sadar Upazila', N'ঝিনাইদহ সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (358, 58, N'Maheshpur Upazila', N'মহেশপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (359, 58, N'Kaliganj Upazila', N'কালীগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (360, 58, N'Kotchandpur Upazila', N'কোট চাঁদপুর ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (361, 58, N'Shailkupa Upazila', N'শৈলকুপা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (362, 58, N'Harinakunda Upazila', N'হাড়িনাকুন্দা')
                GO
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (363, 59, N'Terokhada Upazila', N'তেরোখাদা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (364, 59, N'Batiaghata Upazila', N'বাটিয়াঘাটা ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (365, 59, N'Dacope Upazila', N'ডাকপে')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (366, 59, N'Dumuria Upazila', N'ডুমুরিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (367, 59, N'Dighalia Upazila', N'দিঘলিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (368, 59, N'Koyra Upazila', N'কয়ড়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (369, 59, N'Paikgachha Upazila', N'পাইকগাছা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (370, 59, N'Phultala Upazila', N'ফুলতলা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (371, 59, N'Rupsa Upazila', N'রূপসা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (372, 59, N'Aranghata', N'আড়াংঘাটা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (373, 59, N'Daulatpur', N'দৌলতপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (374, 59, N'Harintana', N'হারিন্তানা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (375, 59, N'Horintana', N'হরিণতানা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (376, 59, N'Khalishpur', N'খালিশপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (377, 59, N'Khanjahan Ali', N'খানজাহান আলী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (378, 59, N'Khulna Sadar', N'খুলনা সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (379, 59, N'Labanchora', N'লাবানছোরা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (380, 59, N'Sonadanga', N'সোনাডাঙ্গা')


                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (381, 60, N'Kushtia Sadar', N'কুষ্টিয়া সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (382, 60, N'Kumarkhali', N'কুমারখালি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (383, 60, N'Daulatpur', N'দৌলতপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (384, 60, N'Mirpur', N'মিরপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (385, 60, N'Bheramara', N'ভেরামারা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (386, 60, N'Khoksa', N'খোকসা')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (387, 61, N'Magura Sadar Upazila', N'মাগুরা সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (388, 61, N'Mohammadpur Upazila', N'মোহাম্মাদপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (389, 61, N'Shalikha Upazila', N'শালিখা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (390, 61, N'Sreepur Upazila', N'শ্রীপুর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (391, 62, N'angni Upazila', N'আংনি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (392, 62, N'Mujib Nagar Upazila', N'মুজিব নগর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (393, 62, N'Meherpur-S Upazila', N'মেহেরপুর সদর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (394, 63, N'Narail-S Upazilla', N'নড়াইল সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (395, 63, N'Lohagara Upazilla', N'লোহাগাড়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (396, 63, N'Kalia Upazilla', N'কালিয়া')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (397, 64, N'Satkhira Sadar Upazila', N'সাতক্ষীরা সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (398, 64, N'Assasuni Upazila', N'আসসাশুনি ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (399, 64, N'Debhata Upazila', N'দেভাটা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (400, 64, N'Tala Upazila', N'তালা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (401, 64, N'Kalaroa Upazila', N'কলরোয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (402, 64, N'Kaliganj Upazila', N'কালীগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (403, 64, N'Shyamnagar Upazila', N'শ্যামনগর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (405, 18, N'Adamdighi', N'আদমদিঘী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (406, 18, N'Bogra Sadar', N'বগুড়া সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (407, 18, N'Sherpur', N'শেরপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (408, 18, N'Dhunat', N'ধুনট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (409, 18, N'Dhupchanchia', N'দুপচাচিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (410, 18, N'Gabtali', N'গাবতলি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (411, 18, N'Kahaloo', N'কাহালু')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (412, 18, N'Nandigram', N'নন্দিগ্রাম')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (413, 18, N'Sahajanpur', N'শাহজাহানপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (414, 18, N'Sariakandi', N'সারিয়াকান্দি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (415, 18, N'Shibganj', N'শিবগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (416, 18, N'Sonatala', N'সোনাতলা')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (417, 19, N'Joypurhat S', N'জয়পুরহাট সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (418, 19, N'Akkelpur', N'আক্কেলপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (419, 19, N'Kalai', N'কালাই')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (420, 19, N'Khetlal', N'খেতলাল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (421, 19, N'Panchbibi', N'পাঁচবিবি')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (422, 20, N'Naogaon Sadar Upazila', N'নওগাঁ সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (423, 20, N'Mohadevpur Upazila', N'মহাদেবপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (424, 20, N'Manda Upazila', N'মান্দা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (425, 20, N'Niamatpur Upazila', N'নিয়ামতপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (426, 20, N'Atrai Upazila', N'আত্রাই')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (427, 20, N'Raninagar Upazila', N'রাণীনগর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (428, 20, N'Patnitala Upazila', N'পত্নীতলা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (429, 20, N'Dhamoirhat Upazila', N'ধামইরহাট ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (430, 20, N'Sapahar Upazila', N'সাপাহার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (431, 20, N'Porsha Upazila', N'পোরশা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (432, 20, N'Badalgachhi Upazila', N'বদলগাছি')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (433, 21, N'Natore Sadar Upazila', N'নাটোর সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (434, 21, N'Baraigram Upazila', N'বড়াইগ্রাম')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (435, 21, N'Bagatipara Upazila', N'বাগাতিপাড়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (436, 21, N'Lalpur Upazila', N'লালপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (437, 21, N'Natore Sadar Upazila', N'নাটোর সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (438, 21, N'Baraigram Upazila', N'বড়াই গ্রাম')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (439, 22, N'Bholahat Upazila', N'ভোলাহাট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (440, 22, N'Gomastapur Upazila', N'গোমস্তাপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (441, 22, N'Nachole Upazila', N'নাচোল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (442, 22, N'Nawabganj Sadar Upazila', N'নবাবগঞ্জ সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (443, 22, N'Shibganj Upazila', N'শিবগঞ্জ')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (444, 23, N'Atgharia Upazila', N'আটঘরিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (445, 23, N'Bera Upazila', N'বেড়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (446, 23, N'Bhangura Upazila', N'ভাঙ্গুরা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (447, 23, N'Chatmohar Upazila', N'চাটমোহর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (448, 23, N'Faridpur Upazila', N'ফরিদপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (449, 23, N'Ishwardi Upazila', N'ঈশ্বরদী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (450, 23, N'Pabna Sadar Upazila', N'পাবনা সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (451, 23, N'Santhia Upazila', N'সাথিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (452, 23, N'Sujanagar Upazila', N'সুজানগর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (453, 24, N'Bagha', N'বাঘা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (454, 24, N'Bagmara', N'বাগমারা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (455, 24, N'Charghat', N'চারঘাট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (456, 24, N'Durgapur', N'দুর্গাপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (457, 24, N'Godagari', N'গোদাগারি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (458, 24, N'Mohanpur', N'মোহনপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (459, 24, N'Paba', N'পবা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (460, 24, N'Puthia', N'পুঠিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (461, 24, N'Tanore', N'তানোর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (462, 24, N'Boalia', N'বোয়ালিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (463, 24, N'Motihar', N'মতিহার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (464, 24, N'Shahmokhdum', N'শাহ্ মকখদুম')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (465, 24, N'Rajpara', N'রাজপারা')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (466, 25, N'Sirajganj Sadar Upazila', N'সিরাজগঞ্জ সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (467, 25, N'Belkuchi Upazila', N'বেলকুচি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (468, 25, N'Chauhali Upazila', N'চৌহালি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (469, 25, N'Kamarkhanda Upazila', N'কামারখান্দা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (470, 25, N'Kazipur Upazila', N'কাজীপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (471, 25, N'Raiganj Upazila', N'রায়গঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (472, 25, N'Shahjadpur Upazila', N'শাহজাদপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (473, 25, N'Tarash Upazila', N'তারাশ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (474, 25, N'Ullahpara Upazila', N'উল্লাপাড়া')
                GO
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (475, 26, N'Birampur Upazila', N'বিরামপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (476, 26, N'Birganj', N'বীরগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (477, 26, N'Biral Upazila', N'বিড়াল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (478, 26, N'Bochaganj Upazila', N'বোচাগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (479, 26, N'Chirirbandar Upazila', N'চিরিরবন্দর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (480, 26, N'Phulbari Upazila', N'ফুলবাড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (481, 26, N'Ghoraghat Upazila', N'ঘোড়াঘাট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (482, 26, N'Hakimpur Upazila', N'হাকিমপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (483, 26, N'Kaharole Upazila', N'কাহারোল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (484, 26, N'Khansama Upazila', N'খানসামা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (485, 26, N'Dinajpur Sadar Upazila', N'দিনাজপুর সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (486, 26, N'Nawabganj', N'নবাবগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (487, 26, N'Parbatipur Upazila', N'পার্বতীপুর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (488, 27, N'Fulchhari', N'ফুলছড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (489, 27, N'Gaibandha sadar', N'গাইবান্ধা সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (490, 27, N'Gobindaganj', N'গোবিন্দগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (491, 27, N'Palashbari', N'পলাশবাড়ী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (492, 27, N'Sadullapur', N'সাদুল্যাপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (493, 27, N'Saghata', N'সাঘাটা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (494, 27, N'Sundarganj', N'সুন্দরগঞ্জ')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (495, 28, N'Kurigram Sadar', N'কুড়িগ্রাম সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (496, 28, N'Nageshwari', N'নাগেশ্বরী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (497, 28, N'Bhurungamari', N'ভুরুঙ্গামারি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (498, 28, N'Phulbari', N'ফুলবাড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (499, 28, N'Rajarhat', N'রাজারহাট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (500, 28, N'Ulipur', N'উলিপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (501, 28, N'Chilmari', N'চিলমারি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (502, 28, N'Rowmari', N'রউমারি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (503, 28, N'Char Rajibpur', N'চর রাজিবপুর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (504, 29, N'Lalmanirhat Sadar', N'লালমনিরহাট সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (505, 29, N'Aditmari', N'আদিতমারি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (506, 29, N'Kaliganj', N'কালীগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (507, 29, N'Hatibandha', N'হাতিবান্ধা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (508, 29, N'Patgram', N'পাটগ্রাম')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (509, 30, N'Nilphamari Sadar', N'নীলফামারী সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (510, 30, N'Saidpur', N'সৈয়দপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (511, 30, N'Jaldhaka', N'জলঢাকা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (512, 30, N'Kishoreganj', N'কিশোরগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (513, 30, N'Domar', N'ডোমার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (514, 30, N'Dimla', N'ডিমলা')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (515, 31, N'Panchagarh Sadar', N'পঞ্চগড় সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (516, 31, N'Debiganj', N'দেবীগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (517, 31, N'Boda', N'বোদা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (518, 31, N'Atwari', N'আটোয়ারি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (519, 31, N'Tetulia', N'তেতুলিয়া')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (520, 32, N'Badarganj', N'বদরগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (521, 32, N'Mithapukur', N'মিঠাপুকুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (522, 32, N'Gangachara', N'গঙ্গাচরা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (523, 32, N'Kaunia', N'কাউনিয়া')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (524, 32, N'Rangpur Sadar', N'রংপুর সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (525, 32, N'Pirgachha', N'পীরগাছা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (526, 32, N'Pirganj', N'পীরগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (527, 32, N'Taraganj', N'তারাগঞ্জ')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (528, 33, N'Thakurgaon Sadar Upazila', N'ঠাকুরগাঁও সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (529, 33, N'Pirganj Upazila', N'পীরগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (530, 33, N'Baliadangi Upazila', N'বালিয়াডাঙ্গি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (531, 33, N'Haripur Upazila', N'হরিপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (532, 33, N'Ranisankail Upazila', N'রাণীসংকইল')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (533, 51, N'Ajmiriganj', N'আজমিরিগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (534, 51, N'Baniachang', N'বানিয়াচং')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (535, 51, N'Bahubal', N'বাহুবল')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (536, 51, N'Chunarughat', N'চুনারুঘাট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (537, 51, N'Habiganj Sadar', N'হবিগঞ্জ সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (538, 51, N'Lakhai', N'লাক্ষাই')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (539, 51, N'Madhabpur', N'মাধবপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (540, 51, N'Nabiganj', N'নবীগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (541, 51, N'Shaistagonj Upazila', N'শায়েস্তাগঞ্জ')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (542, 52, N'Moulvibazar Sadar', N'মৌলভীবাজার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (543, 52, N'Barlekha', N'বড়লেখা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (544, 52, N'Juri', N'জুড়ি')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (545, 52, N'Kamalganj', N'কামালগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (546, 52, N'Kulaura', N'কুলাউরা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (547, 52, N'Rajnagar', N'রাজনগর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (548, 52, N'Sreemangal', N'শ্রীমঙ্গল')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (549, 53, N'Bishwamvarpur', N'বিসশম্ভারপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (550, 53, N'Chhatak', N'ছাতক')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (551, 53, N'Derai', N'দেড়াই')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (552, 53, N'Dharampasha', N'ধরমপাশা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (553, 53, N'Dowarabazar', N'দোয়ারাবাজার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (554, 53, N'Jagannathpur', N'জগন্নাথপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (555, 53, N'Jamalganj', N'জামালগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (556, 53, N'Sulla', N'সুল্লা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (557, 53, N'Sunamganj Sadar', N'সুনামগঞ্জ সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (558, 53, N'Shanthiganj', N'শান্তিগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (559, 53, N'Tahirpur', N'তাহিরপুর')

                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (560, 54, N'Sylhet Sadar', N'সিলেট সদর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (561, 54, N'Beanibazar', N'বেয়ানিবাজার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (562, 54, N'Bishwanath', N'বিশ্বনাথ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (563, 54, N'Dakshin Surma Upazila', N'দক্ষিণ সুরমা')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (564, 54, N'Balaganj', N'বালাগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (565, 54, N'Companiganj', N'কোম্পানিগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (566, 54, N'Fenchuganj', N'ফেঞ্চুগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (567, 54, N'Golapganj', N'গোলাপগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (568, 54, N'Gowainghat', N'গোয়াইনঘাট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (569, 54, N'Jaintiapur', N'জয়ন্তপুর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (570, 54, N'Kanaighat', N'কানাইঘাট')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (571, 54, N'Zakiganj', N'জাকিগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (572, 54, N'Nobigonj', N'নবীগঞ্জ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (573, 54, N'Airport', N'বিমানবন্দর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (574, 54, N'Hazrat Shah Paran', N'হযরত শাহ পরাণ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (575, 54, N'Jalalabad', N'জালালাবাদ')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (576, 54, N'Kowtali', N'কোতোয়ালী')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (577, 54, N'Moglabazar', N'মোগলাবাজার')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (578, 54, N'Osmani Nagar', N'ওসমানী নগর')
                INSERT [dbo].[Upazilas] ([Id], [DistrictId], [Name], [BnName]) VALUES (579, 54, N'South Surma', N'দক্ষিণ সুরমা')
                SET IDENTITY_INSERT [dbo].[Upazilas] OFF");
        }
        
        public override void Down()
        {
            Sql(@"DELETE FROM Upazilas;
                   DBCC CHECKIDENT ('Upazilas', RESEED, 0)");
        }
    }
}
