// <auto-generated />
namespace RMS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Notificatin_Model_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Notificatin_Model_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201809202006058_Notificatin_Model_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
